# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 604871f7c1fb227abb060511a4b45861c3d3e0cbd1581ded97603b76eea1b532152271edbe90097804c18ea1f99a60bfec32bbf91c27058d273570463579137a

test:
  secret_key_base: bf6d24c319de68a3352f71af5a5541fea9968a9c7565ef69d67e8d8d285b929b08abb22b28dc8b38ebab7046e0faa377bf3f0c26be3f80a06633df69bfeb0b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
